#####################################################################################################################################################
######################################################################## INFO #######################################################################
#####################################################################################################################################################

# This is a needed workflow file for the PyRat software.
# It allows the automatic publication of the documentation on GitHub Pages at each push.

#####################################################################################################################################################
###################################################################### CONTENTS #####################################################################
#####################################################################################################################################################

# .github/workflows/docs.yml
name: Build and Deploy Docs

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true

      - name: Install Python and dependencies
        run: uv sync --extra docs

      - name: Build documentation
        run: uv run make -C docs html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

#####################################################################################################################################################
#####################################################################################################################################################